# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 683)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SearchpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchpushButton.setGeometry(QtCore.QRect(560, 10, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchpushButton.sizePolicy().hasHeightForWidth())
        self.SearchpushButton.setSizePolicy(sizePolicy)
        self.SearchpushButton.setObjectName("SearchpushButton")
        self.SearchcomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.SearchcomboBox.setGeometry(QtCore.QRect(450, 10, 90, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchcomboBox.sizePolicy().hasHeightForWidth())
        self.SearchcomboBox.setSizePolicy(sizePolicy)
        self.SearchcomboBox.setMinimumSize(QtCore.QSize(90, 0))
        self.SearchcomboBox.setObjectName("SearchcomboBox")
        self.SearchcomboBox.addItem("")
        self.SearchcomboBox.addItem("")
        self.SearchcomboBox.addItem("")
        self.SearchlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchlineEdit.setGeometry(QtCore.QRect(20, 10, 431, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchlineEdit.sizePolicy().hasHeightForWidth())
        self.SearchlineEdit.setSizePolicy(sizePolicy)
        self.SearchlineEdit.setObjectName("SearchlineEdit")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(720, 50, 321, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.TeamMsggroupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.TeamMsggroupBox.setObjectName("TeamMsggroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.TeamMsggroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.TeamMsggroupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.TeamName = QtWidgets.QLabel(self.TeamMsggroupBox)
        self.TeamName.setText("")
        self.TeamName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TeamName.setObjectName("TeamName")
        self.horizontalLayout_6.addWidget(self.TeamName)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.TeamMsggroupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.TeamAssi = QtWidgets.QLabel(self.TeamMsggroupBox)
        self.TeamAssi.setText("")
        self.TeamAssi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TeamAssi.setObjectName("TeamAssi")
        self.horizontalLayout_10.addWidget(self.TeamAssi)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.TeamMsggroupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.TeamMember = QtWidgets.QLabel(self.TeamMsggroupBox)
        self.TeamMember.setText("")
        self.TeamMember.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TeamMember.setObjectName("TeamMember")
        self.horizontalLayout_7.addWidget(self.TeamMember)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.TeamMsggroupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.TeamVote = QtWidgets.QLabel(self.TeamMsggroupBox)
        self.TeamVote.setText("")
        self.TeamVote.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TeamVote.setObjectName("TeamVote")
        self.horizontalLayout_8.addWidget(self.TeamVote)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.TeamMsggroupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.TeamScore = QtWidgets.QLineEdit(self.TeamMsggroupBox)
        self.TeamScore.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TeamScore.setObjectName("TeamScore")
        self.horizontalLayout_9.addWidget(self.TeamScore)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.addWidget(self.TeamMsggroupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.inputScorepushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputScorepushButton.sizePolicy().hasHeightForWidth())
        self.inputScorepushButton.setSizePolicy(sizePolicy)
        self.inputScorepushButton.setMaximumSize(QtCore.QSize(93, 16777215))
        self.inputScorepushButton.setObjectName("inputScorepushButton")
        self.horizontalLayout_3.addWidget(self.inputScorepushButton)
        self.VoteTeampushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VoteTeampushButton.sizePolicy().hasHeightForWidth())
        self.VoteTeampushButton.setSizePolicy(sizePolicy)
        self.VoteTeampushButton.setMaximumSize(QtCore.QSize(93, 16777215))
        self.VoteTeampushButton.setObjectName("VoteTeampushButton")
        self.horizontalLayout_3.addWidget(self.VoteTeampushButton)
        self.DelTeamMsgpushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DelTeamMsgpushButton.sizePolicy().hasHeightForWidth())
        self.DelTeamMsgpushButton.setSizePolicy(sizePolicy)
        self.DelTeamMsgpushButton.setMaximumSize(QtCore.QSize(93, 16777215))
        self.DelTeamMsgpushButton.setObjectName("DelTeamMsgpushButton")
        self.horizontalLayout_3.addWidget(self.DelTeamMsgpushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.StuAddpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.StuAddpushButton.setGeometry(QtCore.QRect(720, 580, 131, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StuAddpushButton.sizePolicy().hasHeightForWidth())
        self.StuAddpushButton.setSizePolicy(sizePolicy)
        self.StuAddpushButton.setObjectName("StuAddpushButton")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(720, 310, 321, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.StuMsggroupBox = QtWidgets.QGroupBox(self.layoutWidget1)
        self.StuMsggroupBox.setObjectName("StuMsggroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.StuMsggroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.StuMsggroupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.StuName = QtWidgets.QLabel(self.StuMsggroupBox)
        self.StuName.setText("")
        self.StuName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StuName.setObjectName("StuName")
        self.horizontalLayout_2.addWidget(self.StuName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.StuMsggroupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.StuNum = QtWidgets.QLabel(self.StuMsggroupBox)
        self.StuNum.setText("")
        self.StuNum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StuNum.setObjectName("StuNum")
        self.horizontalLayout_4.addWidget(self.StuNum)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.StuMsggroupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.StuMajor = QtWidgets.QLabel(self.StuMsggroupBox)
        self.StuMajor.setText("")
        self.StuMajor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StuMajor.setObjectName("StuMajor")
        self.horizontalLayout_5.addWidget(self.StuMajor)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.StuMsggroupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DelStuMsgpushButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DelStuMsgpushButton.sizePolicy().hasHeightForWidth())
        self.DelStuMsgpushButton.setSizePolicy(sizePolicy)
        self.DelStuMsgpushButton.setMaximumSize(QtCore.QSize(93, 16777215))
        self.DelStuMsgpushButton.setObjectName("DelStuMsgpushButton")
        self.horizontalLayout.addWidget(self.DelStuMsgpushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.TchAddpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.TchAddpushButton.setGeometry(QtCore.QRect(720, 540, 131, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TchAddpushButton.sizePolicy().hasHeightForWidth())
        self.TchAddpushButton.setSizePolicy(sizePolicy)
        self.TchAddpushButton.setObjectName("TchAddpushButton")
        self.refresh_data = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_data.setGeometry(QtCore.QRect(670, 10, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh_data.sizePolicy().hasHeightForWidth())
        self.refresh_data.setSizePolicy(sizePolicy)
        self.refresh_data.setObjectName("refresh_data")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 360, 671, 261))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 50, 671, 301))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.AllMsgtreeWidget = QtWidgets.QTreeWidget(self.groupBox_2)
        self.AllMsgtreeWidget.setObjectName("AllMsgtreeWidget")
        self.AllMsgtreeWidget.headerItem().setText(0, "1")
        self.gridLayout_3.addWidget(self.AllMsgtreeWidget, 0, 0, 1, 1)
        self.deleteDBButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteDBButton.setGeometry(QtCore.QRect(910, 580, 131, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteDBButton.sizePolicy().hasHeightForWidth())
        self.deleteDBButton.setSizePolicy(sizePolicy)
        self.deleteDBButton.setObjectName("deleteDBButton")
        self.layoutWidget.raise_()
        self.SearchpushButton.raise_()
        self.SearchcomboBox.raise_()
        self.SearchlineEdit.raise_()
        self.layoutWidget.raise_()
        self.StuAddpushButton.raise_()
        self.TchAddpushButton.raise_()
        self.refresh_data.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.deleteDBButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 26))
        self.menubar.setObjectName("menubar")
        self.menuHF = QtWidgets.QMenu(self.menubar)
        self.menuHF.setObjectName("menuHF")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionX = QtWidgets.QAction(MainWindow)
        self.actionX.setObjectName("actionX")
        self.menuHF.addAction(self.actionX)
        self.menubar.addAction(self.menuHF.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SearchpushButton.setText(_translate("MainWindow", "搜索..."))
        self.SearchcomboBox.setItemText(0, _translate("MainWindow", "课设题目"))
        self.SearchcomboBox.setItemText(1, _translate("MainWindow", "专业"))
        self.SearchcomboBox.setItemText(2, _translate("MainWindow", "学生姓名"))
        self.TeamMsggroupBox.setTitle(_translate("MainWindow", "小组信息"))
        self.label_4.setText(_translate("MainWindow", "小组名:"))
        self.label_8.setText(_translate("MainWindow", "选题:"))
        self.label_5.setText(_translate("MainWindow", "成员:"))
        self.label_6.setText(_translate("MainWindow", "得票数:"))
        self.label_7.setText(_translate("MainWindow", "成绩:"))
        self.inputScorepushButton.setText(_translate("MainWindow", "录入成绩"))
        self.VoteTeampushButton.setText(_translate("MainWindow", "投票"))
        self.DelTeamMsgpushButton.setText(_translate("MainWindow", "删除"))
        self.StuAddpushButton.setText(_translate("MainWindow", "学生添加分组信息"))
        self.StuMsggroupBox.setTitle(_translate("MainWindow", "学生信息"))
        self.label.setText(_translate("MainWindow", "姓名:"))
        self.label_2.setText(_translate("MainWindow", "学号:"))
        self.label_3.setText(_translate("MainWindow", "专业:"))
        self.DelStuMsgpushButton.setText(_translate("MainWindow", "删除"))
        self.TchAddpushButton.setText(_translate("MainWindow", "老师添加课程信息"))
        self.refresh_data.setText(_translate("MainWindow", "刷新数据"))
        self.groupBox.setTitle(_translate("MainWindow", "题目信息"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "题目"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "小组"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "学生"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "成绩"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "得票数"))
        self.groupBox_2.setTitle(_translate("MainWindow", "全局信息"))
        self.deleteDBButton.setText(_translate("MainWindow", "清空数据库"))
        self.menuHF.setTitle(_translate("MainWindow", "系统"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.actionX.setText(_translate("MainWindow", "Exit"))

