# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_StuAddMsgBox.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StuAddMsgBox(object):
    def setupUi(self, StuAddMsgBox):
        StuAddMsgBox.setObjectName("StuAddMsgBox")
        StuAddMsgBox.resize(545, 288)
        self.splitter_2 = QtWidgets.QSplitter(StuAddMsgBox)
        self.splitter_2.setGeometry(QtCore.QRect(20, 86, 499, 21))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_8 = QtWidgets.QLabel(self.splitter_2)
        self.label_8.setObjectName("label_8")
        self.MajorcomboBox_2 = QtWidgets.QComboBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MajorcomboBox_2.sizePolicy().hasHeightForWidth())
        self.MajorcomboBox_2.setSizePolicy(sizePolicy)
        self.MajorcomboBox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.MajorcomboBox_2.setObjectName("MajorcomboBox_2")
        self.MajorcomboBox_2.addItem("")
        self.MajorcomboBox_2.setItemText(0, "")
        self.label_5 = QtWidgets.QLabel(self.splitter_2)
        self.label_5.setObjectName("label_5")
        self.MsgBoxNamelineEdit_2 = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MsgBoxNamelineEdit_2.sizePolicy().hasHeightForWidth())
        self.MsgBoxNamelineEdit_2.setSizePolicy(sizePolicy)
        self.MsgBoxNamelineEdit_2.setObjectName("MsgBoxNamelineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.splitter_2)
        self.label_6.setObjectName("label_6")
        self.MsgBoxNumlineEdit_2 = QtWidgets.QLineEdit(self.splitter_2)
        self.MsgBoxNumlineEdit_2.setObjectName("MsgBoxNumlineEdit_2")
        self.splitter_3 = QtWidgets.QSplitter(StuAddMsgBox)
        self.splitter_3.setGeometry(QtCore.QRect(20, 142, 499, 21))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_9 = QtWidgets.QLabel(self.splitter_3)
        self.label_9.setObjectName("label_9")
        self.MajorcomboBox_4 = QtWidgets.QComboBox(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MajorcomboBox_4.sizePolicy().hasHeightForWidth())
        self.MajorcomboBox_4.setSizePolicy(sizePolicy)
        self.MajorcomboBox_4.setMinimumSize(QtCore.QSize(150, 0))
        self.MajorcomboBox_4.setObjectName("MajorcomboBox_4")
        self.MajorcomboBox_4.addItem("")
        self.MajorcomboBox_4.setItemText(0, "")
        self.label_10 = QtWidgets.QLabel(self.splitter_3)
        self.label_10.setObjectName("label_10")
        self.MsgBoxNamelineEdit_4 = QtWidgets.QLineEdit(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MsgBoxNamelineEdit_4.sizePolicy().hasHeightForWidth())
        self.MsgBoxNamelineEdit_4.setSizePolicy(sizePolicy)
        self.MsgBoxNamelineEdit_4.setObjectName("MsgBoxNamelineEdit_4")
        self.label_11 = QtWidgets.QLabel(self.splitter_3)
        self.label_11.setObjectName("label_11")
        self.MsgBoxNumlineEdit_4 = QtWidgets.QLineEdit(self.splitter_3)
        self.MsgBoxNumlineEdit_4.setObjectName("MsgBoxNumlineEdit_4")
        self.splitter_4 = QtWidgets.QSplitter(StuAddMsgBox)
        self.splitter_4.setGeometry(QtCore.QRect(20, 198, 499, 21))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_18 = QtWidgets.QLabel(self.splitter_4)
        self.label_18.setObjectName("label_18")
        self.MajorcomboBox_6 = QtWidgets.QComboBox(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MajorcomboBox_6.sizePolicy().hasHeightForWidth())
        self.MajorcomboBox_6.setSizePolicy(sizePolicy)
        self.MajorcomboBox_6.setMinimumSize(QtCore.QSize(150, 0))
        self.MajorcomboBox_6.setObjectName("MajorcomboBox_6")
        self.MajorcomboBox_6.addItem("")
        self.MajorcomboBox_6.setItemText(0, "")
        self.label_19 = QtWidgets.QLabel(self.splitter_4)
        self.label_19.setObjectName("label_19")
        self.MsgBoxNamelineEdit_6 = QtWidgets.QLineEdit(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MsgBoxNamelineEdit_6.sizePolicy().hasHeightForWidth())
        self.MsgBoxNamelineEdit_6.setSizePolicy(sizePolicy)
        self.MsgBoxNamelineEdit_6.setObjectName("MsgBoxNamelineEdit_6")
        self.label_20 = QtWidgets.QLabel(self.splitter_4)
        self.label_20.setObjectName("label_20")
        self.MsgBoxNumlineEdit_6 = QtWidgets.QLineEdit(self.splitter_4)
        self.MsgBoxNumlineEdit_6.setObjectName("MsgBoxNumlineEdit_6")
        self.splitter_5 = QtWidgets.QSplitter(StuAddMsgBox)
        self.splitter_5.setGeometry(QtCore.QRect(20, 170, 499, 21))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_21 = QtWidgets.QLabel(self.splitter_5)
        self.label_21.setObjectName("label_21")
        self.MajorcomboBox_5 = QtWidgets.QComboBox(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MajorcomboBox_5.sizePolicy().hasHeightForWidth())
        self.MajorcomboBox_5.setSizePolicy(sizePolicy)
        self.MajorcomboBox_5.setMinimumSize(QtCore.QSize(150, 0))
        self.MajorcomboBox_5.setObjectName("MajorcomboBox_5")
        self.MajorcomboBox_5.addItem("")
        self.MajorcomboBox_5.setItemText(0, "")
        self.label_22 = QtWidgets.QLabel(self.splitter_5)
        self.label_22.setObjectName("label_22")
        self.MsgBoxNamelineEdit_5 = QtWidgets.QLineEdit(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MsgBoxNamelineEdit_5.sizePolicy().hasHeightForWidth())
        self.MsgBoxNamelineEdit_5.setSizePolicy(sizePolicy)
        self.MsgBoxNamelineEdit_5.setObjectName("MsgBoxNamelineEdit_5")
        self.label_23 = QtWidgets.QLabel(self.splitter_5)
        self.label_23.setObjectName("label_23")
        self.MsgBoxNumlineEdit_5 = QtWidgets.QLineEdit(self.splitter_5)
        self.MsgBoxNumlineEdit_5.setObjectName("MsgBoxNumlineEdit_5")
        self.StuAddOkButton = QtWidgets.QPushButton(StuAddMsgBox)
        self.StuAddOkButton.setGeometry(QtCore.QRect(370, 240, 71, 28))
        self.StuAddOkButton.setObjectName("StuAddOkButton")
        self.StuAddCloseButton = QtWidgets.QPushButton(StuAddMsgBox)
        self.StuAddCloseButton.setGeometry(QtCore.QRect(450, 240, 71, 28))
        self.StuAddCloseButton.setObjectName("StuAddCloseButton")
        self.splitter = QtWidgets.QSplitter(StuAddMsgBox)
        self.splitter.setGeometry(QtCore.QRect(20, 58, 499, 21))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_7 = QtWidgets.QLabel(self.splitter)
        self.label_7.setObjectName("label_7")
        self.MajorcomboBox_1 = QtWidgets.QComboBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MajorcomboBox_1.sizePolicy().hasHeightForWidth())
        self.MajorcomboBox_1.setSizePolicy(sizePolicy)
        self.MajorcomboBox_1.setMinimumSize(QtCore.QSize(150, 0))
        self.MajorcomboBox_1.setObjectName("MajorcomboBox_1")
        self.MajorcomboBox_1.addItem("")
        self.MajorcomboBox_1.setItemText(0, "")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.MsgBoxNamelineEdit_1 = QtWidgets.QLineEdit(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MsgBoxNamelineEdit_1.sizePolicy().hasHeightForWidth())
        self.MsgBoxNamelineEdit_1.setSizePolicy(sizePolicy)
        self.MsgBoxNamelineEdit_1.setObjectName("MsgBoxNamelineEdit_1")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.MsgBoxNumlineEdit_1 = QtWidgets.QLineEdit(self.splitter)
        self.MsgBoxNumlineEdit_1.setObjectName("MsgBoxNumlineEdit_1")
        self.label_12 = QtWidgets.QLabel(StuAddMsgBox)
        self.label_12.setGeometry(QtCore.QRect(20, 114, 30, 16))
        self.label_12.setObjectName("label_12")
        self.MajorcomboBox_3 = QtWidgets.QComboBox(StuAddMsgBox)
        self.MajorcomboBox_3.setGeometry(QtCore.QRect(56, 114, 150, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MajorcomboBox_3.sizePolicy().hasHeightForWidth())
        self.MajorcomboBox_3.setSizePolicy(sizePolicy)
        self.MajorcomboBox_3.setMinimumSize(QtCore.QSize(150, 0))
        self.MajorcomboBox_3.setObjectName("MajorcomboBox_3")
        self.MajorcomboBox_3.addItem("")
        self.MajorcomboBox_3.setItemText(0, "")
        self.label_13 = QtWidgets.QLabel(StuAddMsgBox)
        self.label_13.setGeometry(QtCore.QRect(212, 114, 30, 16))
        self.label_13.setObjectName("label_13")
        self.MsgBoxNamelineEdit_3 = QtWidgets.QLineEdit(StuAddMsgBox)
        self.MsgBoxNamelineEdit_3.setGeometry(QtCore.QRect(248, 114, 115, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MsgBoxNamelineEdit_3.sizePolicy().hasHeightForWidth())
        self.MsgBoxNamelineEdit_3.setSizePolicy(sizePolicy)
        self.MsgBoxNamelineEdit_3.setObjectName("MsgBoxNamelineEdit_3")
        self.label_14 = QtWidgets.QLabel(StuAddMsgBox)
        self.label_14.setGeometry(QtCore.QRect(369, 114, 30, 16))
        self.label_14.setObjectName("label_14")
        self.MsgBoxNumlineEdit_3 = QtWidgets.QLineEdit(StuAddMsgBox)
        self.MsgBoxNumlineEdit_3.setGeometry(QtCore.QRect(405, 114, 114, 21))
        self.MsgBoxNumlineEdit_3.setObjectName("MsgBoxNumlineEdit_3")
        self.layoutWidget = QtWidgets.QWidget(StuAddMsgBox)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 20, 219, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.AssicomboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AssicomboBox.sizePolicy().hasHeightForWidth())
        self.AssicomboBox.setSizePolicy(sizePolicy)
        self.AssicomboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.AssicomboBox.setObjectName("AssicomboBox")
        self.AssicomboBox.addItem("")
        self.AssicomboBox.setItemText(0, "")
        self.horizontalLayout_2.addWidget(self.AssicomboBox)
        self.layoutWidget1 = QtWidgets.QWidget(StuAddMsgBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(260, 20, 240, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.MsgBoxTeamNamelineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MsgBoxTeamNamelineEdit.sizePolicy().hasHeightForWidth())
        self.MsgBoxTeamNamelineEdit.setSizePolicy(sizePolicy)
        self.MsgBoxTeamNamelineEdit.setText("")
        self.MsgBoxTeamNamelineEdit.setObjectName("MsgBoxTeamNamelineEdit")
        self.horizontalLayout.addWidget(self.MsgBoxTeamNamelineEdit)

        self.retranslateUi(StuAddMsgBox)
        QtCore.QMetaObject.connectSlotsByName(StuAddMsgBox)

    def retranslateUi(self, StuAddMsgBox):
        _translate = QtCore.QCoreApplication.translate
        StuAddMsgBox.setWindowTitle(_translate("StuAddMsgBox", "Dialog"))
        self.label_8.setText(_translate("StuAddMsgBox", "专业"))
        self.label_5.setText(_translate("StuAddMsgBox", "姓名"))
        self.label_6.setText(_translate("StuAddMsgBox", "学号"))
        self.label_9.setText(_translate("StuAddMsgBox", "专业"))
        self.label_10.setText(_translate("StuAddMsgBox", "姓名"))
        self.label_11.setText(_translate("StuAddMsgBox", "学号"))
        self.label_18.setText(_translate("StuAddMsgBox", "专业"))
        self.label_19.setText(_translate("StuAddMsgBox", "姓名"))
        self.label_20.setText(_translate("StuAddMsgBox", "学号"))
        self.label_21.setText(_translate("StuAddMsgBox", "专业"))
        self.label_22.setText(_translate("StuAddMsgBox", "姓名"))
        self.label_23.setText(_translate("StuAddMsgBox", "学号"))
        self.StuAddOkButton.setText(_translate("StuAddMsgBox", "添加"))
        self.StuAddCloseButton.setText(_translate("StuAddMsgBox", "取消"))
        self.label_7.setText(_translate("StuAddMsgBox", "专业"))
        self.label.setText(_translate("StuAddMsgBox", "姓名"))
        self.label_2.setText(_translate("StuAddMsgBox", "学号"))
        self.label_12.setText(_translate("StuAddMsgBox", "专业"))
        self.label_13.setText(_translate("StuAddMsgBox", "姓名"))
        self.label_14.setText(_translate("StuAddMsgBox", "学号"))
        self.label_3.setText(_translate("StuAddMsgBox", "所选题目"))
        self.label_4.setText(_translate("StuAddMsgBox", "小组名称"))

